# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160721_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
