# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160728_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCompletionTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='completion',
            field=models.ManyToManyField(blank=True, to='accounts.AccountCompletionTask'),
        ),
    ]
