# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20160728_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='quote',
            field=models.TextField(blank=True, null=True),
        ),
    ]
