# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 00:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160729_0708'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 1, 0, 47, 47, 948847, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='skills/logo/'),
        ),
    ]
