# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160801_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='badges/')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='badge',
            name='criteria',
            field=models.ManyToManyField(blank=True, to='accounts.BadgeCriteria'),
        ),
        migrations.AddField(
            model_name='account',
            name='badges',
            field=models.ManyToManyField(blank=True, to='accounts.Badge'),
        ),
    ]
