# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20160802_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
