# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentactivity',
            name='action_type',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('joined', 'Joined')], default='created', max_length=50),
        ),
        migrations.AddField(
            model_name='recentactivity',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='recentactivity',
            name='action',
            field=models.CharField(choices=[('profile', 'Profile'), ('event', 'Event')], default='profile', max_length=50),
        ),
    ]
